server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  output:
    ansi:
      enabled: always
  application:
    name: radar-daemon
  
  profiles:
    active: local-daemon # build.gradle이 구워낸 프로필을 작동시킴

  # 💡 멀티모듈 내부 클래스패스 상의 공통 데이터베이스 속성 결합선 유지
  config:
    use-legacy-processing: true
    import:
      - "optional:classpath*:common-data.yml"

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  devtools:
    livereload:
      enabled: true

# 💡 외부 확장 연동 통로 지정: 런타임 시 외부에 노출된 별도의 log4j2.yml 설정을 바라보도록 구성
logging:
  config: "classpath:log4j2.yml"
  level: # 각 package 별로 로깅 레벨을 지정할 수 있다.
    '[kr.or.kimsn.radar.daemon]': INFO # DEBUG
  pattern:
    console: "%-5level [%d{yyyy-MM-dd HH:mm:ss}] - %msg%n"
    file: "%-5level [%d{yyyy-MM-dd HH:mm:ss}] - %msg%n"
