// 실제 실행되는 메인 모듈이므로 bootJar 활성화
bootJar { enabled = true }
jar { enabled = false }

dependencies {
    // 비즈니스 로직이 담긴 api-module을 가져옴 (api-module이 db-module을 품고 있음)
//    implementation project(':radar-api')
    implementation project(':common-data')

    //thymeleaf layout
    implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect'

    // 웹 서비스 제공을 위한 의존성
    implementation 'org.springframework.boot:spring-boot-starter-web'
    // 필요 시 타임리프 등 추가
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    //spring-boot-devtools .html파일을 컴파일만 해주면 서버 재시작 없이 view 파일 변경이 가능
    implementation 'org.springframework.boot:spring-boot-devtools'

    implementation 'org.springframework.boot:spring-boot-starter-security'

}