// 실제 실행되는 메인 모듈이므로 bootJar 활성화
bootJar { enabled = true }
jar { enabled = false }

dependencies {
    // 비즈니스 로직이 담긴 api-module을 가져옴 (api-module이 db-module을 품고 있음)
//    implementation project(':radar-api')
    implementation project(':common-data')

    implementation 'org.springframework.boot:spring-boot-starter-batch'

    implementation 'org.json:json:20230618'
}