# ====================================================
# 공통 영역 (데몬에 맞게 주석해제)
# ====================================================
# mode= test
mode= real

# 대형 레이더 (/var/opt/edge/ncData/RDR_사이트_RAW_연월일시분.nc)
# rdr_path= /var/opt/edge/ncData
# gubun= 1
# 소형 레이더 (/RDNAS_BK/UF_SQ/연월/일/RDR_사이트_연월일시분.uf)
# rdr_path= /RDNAS_BK/UF_SQ/%yyyyMM%/%dd%/
# gubun=2
# 공항 레이더 (/usr/local/Rainbow5/rainbow/rawdata/264KRC/NCdata/RDR_사이트_RAW__연월일시분.nc)
rdr_path= /usr/local/Rainbow5/rainbow/rawdata/264KRC/NCdata/
gubun=3

# 발신번호
call_from= 027337365

# 템플릿 코드
template_code=radar_0001

# file size (kb)
file_size_min= 999999 # testing
file_size_max= 640350